### ISSUE TITLE
Refactor pwnedPasswordRange to resolve with object?

### ISSUE THREAD

**Issue by textbook** [wKovacs64/hibp#218]
Following on from #24, what if the resolved value from `pwnedPasswordRange` was a simple object mapping the suffixes to the count (`interface PwnedPasswordSuffix { [suffix: string]: number; }`)? E.g. the current test:

https://github.com/wKovacs64/hibp/blob/c92bf7399dcd59b10a817b0207d107ad5e0ff675/src/__tests__/pwnedPasswordRange.test.ts#L14-L27

becomes:

```javascript
      return expect(pwnedPasswordRange('5BAA6')).resolves.toEqual({
        '003D68EB55068C33ACE09247EE4C639306B': 3,
        '1E4C9B93F3F0682250B6CF8331B7EE68FD8': 3303003,
        '01330C689E5D64F660D6947A93AD634EF8F': 1,
      });
```

This would substantially simplify the most common usage, as expressed by the implementation of `pwnedPassword`, from:

https://github.com/wKovacs64/hibp/blob/c92bf7399dcd59b10a817b0207d107ad5e0ff675/src/pwnedPassword.ts#L42-L48

to:

```javascript
  return (
    pwnedPasswordRange(prefix, options)
      .then((arr) => (arr[suffix] || 0))
  );
```

which is also slightly more efficient than an `O(n)` scan of the result array.

I'm happy to PR an implementation if this is a direction people are happy with.

**Comment by wKovacs64** [comment]
Hey @textbook, thanks for your interest in the library!

I would be down with this, sure. 👍 It is a breaking change for direct consumers of `pwnedPasswordRange` (which probably isn't many), but I am planning to release a new semver major version towards the end of the month anyway (to drop Node 10 support), so the timing lines up nicely.

Let me know if you plan to work on it, otherwise I'll get to it in a bit.
