### ISSUE TITLE
Not finding realy simple passwords

### ISSUE THREAD

**Issue by mikhailrojo** [wKovacs64/hibp#35]
Hello

I am trying to check really simple passwords - and no matches found. May be I am doing something wrong?

```js
const hibp = require('hibp');
const sha1 = require('sha1');
const shad = sha1('123456'); // the most simple password

const firstFive = shad.substr(0, 5);
const rest = shad.substr(5);
hibp
    .pwnedPasswordRange(firstFive)
    .then(data => {

        data.forEach(i => {

            if (i.suffix === rest) {
                console.log('FOUND');
            }
        });

    });
```

**Comment by wKovacs64** [comment]
Hey @mikhailrojo, thanks for your interest in the project!

Your `i.suffix === rest` equality check is failing because the [`sha1`](https://www.npmjs.com/package/sha1) package produces lowercase strings, while the remote [Pwned Passwords API](https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange) returns all the suffixes in uppercase. You can either normalize both `i.suffix` and `rest` to uppercase or lowercase, use a case-insensitive regular expression, or use any other case-insensitive string comparison technique.

For example:
```js
if (i.suffix.toLowerCase() === rest) {
  /* ... */
}
```
or
```js
const restRegExp = new RegExp(rest, 'i');

if (restRegExp.test(i.suffix)) {
  /* ... */
}
```

Hope that helps!

**Comment by mikhailrojo** [comment]
Wow Justin

how stupid of me of not thinking about this myself!
thank you and sorry

btw very cool project - I really enjoy it

**Comment by wKovacs64** [comment]
No problem, happy to help. Glad you're enjoying the project!
